name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set Node.js to 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install modules
        run: pnpm install

      - name: Install Prisma client
        run: pnpm exec prisma generate

      - name: Run ESLint
        run: pnpm eslint src/**/*.ts

      - name: Run TypeScript
        run: pnpm tsc --project tsconfig.json --noEmit
